# Generated by Django 4.2.23 on 2025-09-17 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('helpdesk', '0005_initial'),
        ('radio', '0017_alter_subscription_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('ticket_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='helpdesk.ticket')),
                ('request_type', models.CharField(choices=[('VTEI', 'VTEI'), ('VISSI', 'VISSI'), ('VISSI & VTEI', 'VISSI & VTEI')], max_length=20)),
                ('issi_new', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests_as_new', to='radio.issi')),
                ('issi_old', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests_as_old', to='radio.issi')),
                ('radio_old', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests_as_old', to='radio.radio')),
            ],
            bases=('helpdesk.ticket',),
        ),
    ]
