# Generated by Django 4.2.23 on 2025-09-21 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astrid', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='issi_new',
            new_name='new_issi',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='issi_old',
            new_name='old_issi',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='radio_old',
            new_name='old_radio',
        ),
    ]
