# Generated by Django 4.2.23 on 2025-09-23 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astrid', '0002_rename_issi_new_request_new_issi_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'permissions': [('has_access_to_myastrid', 'Heeft toegang tot MyAstrid'), ('can_verify_requests', 'Kan een aanvraag valideren')]},
        ),
    ]
