# Generated by Django 4.2.23 on 2025-09-26 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrid', '0003_alter_request_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='request_type',
            field=models.CharField(choices=[('VTEI', 'VTEI'), ('VISSI', 'VISSI'), ('VISSI & VTEI', 'VISSI & VTEI'), ('ACTIVATION', 'Activation')], max_length=20),
        ),
    ]
