# Generated by Django 4.2.23 on 2026-06-04 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astrid', '0004_alter_request_request_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'permissions': [('has_access_to_myastrid', 'Has access to MyAstrid'), ('can_verify_requests', 'Can validate a request')]},
        ),
    ]
