# Generated by Django 4.2.23 on 2025-07-18 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='external_reference',
            new_name='astrid_ticket',
        ),
    ]
