# Generated by Django 4.2.23 on 2025-07-18 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0002_rename_external_reference_ticket_astrid_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='siamu_ticket',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
