# Generated by Django 4.2.23 on 2025-09-14 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0003_ticket_siamu_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketmessage',
            name='ticket',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
        migrations.DeleteModel(
            name='TicketMessage',
        ),
    ]
