# Generated by Django 4.2.23 on 2025-09-26 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0005_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketlog',
            options={'ordering': ['timestamp']},
        ),
    ]
