# Generated by Django 4.2.23 on 2025-11-01 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0006_alter_ticketlog_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketlog',
            name='note',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ticketlog',
            name='status_after',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_logs', to='helpdesk.ticketstatus'),
        ),
    ]
