# Generated by Django 4.2.23 on 2025-11-01 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0007_alter_ticketlog_note_alter_ticketlog_status_after'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'permissions': [('can_assign_ticket', "Kan het veld 'Assigned to' aanpassen"), ('can_edit_ticket_fields', 'Kan Type, Priority en SIAMU refferece aanpassen')]},
        ),
    ]
