# Generated by Django 4.2.23 on 2025-07-13 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_remove_post_id_remove_post_name_container_parent_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
