# Generated by Django 4.2.23 on 2025-07-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiocontainerlink',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
