# Generated by Django 4.2.23 on 2025-07-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_radiocontainerlink_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiocontainerlink',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
