# Generated by Django 4.2.23 on 2025-07-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_radiocontainerlink_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiocontainerlink',
            name='temporary',
            field=models.BooleanField(default=False),
        ),
    ]
