# Generated by Django 4.2.23 on 2025-07-15 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_radiocontainerlink_temporary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='container',
            options={'ordering': ['name']},
        ),
    ]
