# Generated by Django 4.2.23 on 2025-07-15 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0015_discipline_bootstrap_class'),
        ('organization', '0008_alter_container_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiocontainerlink',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radio_link', to='organization.container'),
        ),
        migrations.AlterField(
            model_name='radiocontainerlink',
            name='radio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='container_link', to='radio.radio'),
        ),
    ]
