# Generated by Django 4.2.23 on 2025-07-15 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_alter_radiocontainerlink_container_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiocontainerlink',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radio_links', to='organization.container'),
        ),
    ]
