# Generated by Django 4.2.23 on 2025-07-16 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0015_discipline_bootstrap_class'),
        ('organization', '0010_alter_radiocontainerlink_container'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiocontainerlink',
            name='radio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='container_link', to='radio.radio'),
        ),
    ]
