# Generated by Django 4.2.23 on 2025-07-16 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0011_alter_radiocontainerlink_radio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='radiocontainerlink',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AddField(
            model_name='radiocontainerlink',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
