# Generated by Django 4.2.23 on 2025-07-21 16:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0012_alter_radiocontainerlink_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiocontainerlink',
            name='scan_interval',
            field=models.DurationField(default=datetime.timedelta(days=1)),
        ),
    ]
