# Generated by Django 4.2.23 on 2025-07-21 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0016_alter_issi_alias'),
        ('organization', '0013_radiocontainerlink_scan_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiocontainerlink',
            name='radio',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='container_link', to='radio.radio'),
        ),
    ]
