# Generated by Django 4.2.23 on 2025-08-29 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0014_alter_radiocontainerlink_radio'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='show_in_listing',
            field=models.BooleanField(default=True),
        ),
    ]
