# Generated by Django 4.2.23 on 2025-11-17 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fireplan', '0003_vehicle_radio'),
        ('organization', '0015_container_show_in_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='vector',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='container', to='fireplan.vector'),
        ),
    ]
