# Generated by Django 4.2.23 on 2026-08-18 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traca', '0002_delete_legacy_slot_models'),
        ('organization', '0016_container_vector'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RadioContainerLink',
        ),
    ]
