# Generated by Django 4.2.23 on 2025-09-07 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('ip', models.GenericIPAddressField()),
                ('backend', models.CharField(choices=[('network', 'Network'), ('linux_kernel', 'Linux Kernel'), ('usb', 'USB')], default='network', max_length=20)),
            ],
        ),
    ]
