# Generated by Django 4.2.23 on 2025-09-07 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='device',
            field=models.CharField(choices=[('QL-500', 'QL-500'), ('QL-550', 'QL-550'), ('QL-560', 'QL-560'), ('QL-570', 'QL-570'), ('QL-580N', 'QL-580N'), ('QL-600', 'QL-600'), ('QL-650TD', 'QL-650TD'), ('QL-700', 'QL-700'), ('QL-710W', 'QL-710W'), ('QL-720NW', 'QL-720NW'), ('QL-800', 'QL-800'), ('QL-810W', 'QL-810W'), ('QL-820NWB', 'QL-820NWB'), ('QL-1050', 'QL-1050'), ('QL-1060N', 'QL-1060N'), ('QL-1100', 'QL-1100'), ('QL-1100NWB', 'QL-1100NWB'), ('QL-1115NWB', 'QL-1115NWB'), ('PT-P750W', 'PT-P750W'), ('PT-P900W', 'PT-P900W'), ('PT-P950NW', 'PT-P950NW'), ('PT-E550W', 'PT-E550W')], default='x', max_length=50),
            preserve_default=False,
        ),
    ]
