# Generated by Django 4.2.23 on 2025-09-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0002_printer_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='dpi',
            field=models.PositiveIntegerField(default=360, help_text='Dots per inch (DPI)'),
        ),
    ]
