# Generated by Django 4.2.23 on 2025-09-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dummy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('can_download_contacts', 'Can download contacts CSV')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
