# Generated by Django 4.2.23 on 2025-09-10 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taqto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('can_download_contacts', 'Can download contacts CSV')],
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.DeleteModel(
            name='Dummy',
        ),
    ]
