# Generated by Django 4.2.23 on 2025-09-20 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taqto', '0002_permissions_delete_dummy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissions',
            options={'default_permissions': (), 'managed': False, 'permissions': [('tacto_user', 'Is allowed to use taqto'), ('can_download_contacts', 'Can download contacts CSV')]},
        ),
    ]
