# Generated by Django 4.2.23 on 2025-10-31 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taqto', '0003_alter_permissions_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Permissions',
        ),
    ]
