# Generated by Django 4.2.23 on 2025-11-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taqto', '0004_delete_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('tacto_user', 'Is allowed to use taqto'), ('can_download_contacts', 'Can download contacts CSV')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
