# Generated by Django 4.2.23 on 2025-07-13 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_post'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryentry',
            name='inventory',
        ),
        migrations.AddField(
            model_name='inventoryentry',
            name='container',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='organization.container'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
