# Generated by Django 4.2.23 on 2025-07-15 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0015_discipline_bootstrap_class'),
        ('inventory', '0002_remove_inventoryentry_inventory_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryentry',
            options={'get_latest_by': 'timestamp', 'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='inventoryentry',
            name='radio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_entries', to='radio.radio'),
        ),
    ]
