# Generated by Django 4.2.23 on 2025-07-15 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventoryentry_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryentry',
            options={'get_latest_by': 'timestamp', 'ordering': ['timestamp']},
        ),
    ]
