# Generated by Django 4.2.23 on 2025-12-24 09:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fireplan', '0005_fireplanfiliere_fireplangrade_fireplangroup_and_more'),
        ('radio', '0022_discipline_discipline_type'),
        ('helpdesk', '0008_alter_ticket_options'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventory', '0004_alter_inventoryentry_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadioContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='LocationContainer',
            fields=[
                ('radiocontainer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.radiocontainer')),
                ('location_type', models.CharField(choices=[('DISPATCH', 'Dispatching'), ('RESERVE', 'Reserve cabinet'), ('STOCK', 'Stock'), ('OTHER', 'Other')], max_length=20)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('inventory.radiocontainer',),
        ),
        migrations.CreateModel(
            name='RadioEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('allows_multiple', models.BooleanField(default=False)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='inventory.radiocontainer')),
                ('primary_radio', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_for_endpoint', to='radio.radio')),
            ],
        ),
        migrations.CreateModel(
            name='RadioAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(choices=[('PRIMARY', 'Primary'), ('TEMP', 'Temporary replacement'), ('STORAGE', 'Storage'), ('REPAIR', 'Repair')], max_length=20)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='inventory.radioendpoint')),
                ('radio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='radio.radio')),
                ('replaces_radio', models.ForeignKey(blank=True, help_text='If TEMP: which primary radio is being replaced.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_by_assignments', to='radio.radio')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='helpdesk.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='VectorContainer',
            fields=[
                ('radiocontainer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.radiocontainer')),
                ('vector', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fireplan.vector')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('inventory.radiocontainer',),
        ),
        migrations.AddConstraint(
            model_name='radioendpoint',
            constraint=models.UniqueConstraint(fields=('container', 'name'), name='uniq_endpoint_per_container'),
        ),
        migrations.AddIndex(
            model_name='radioassignment',
            index=models.Index(fields=['radio', 'end_at'], name='inventory_r_radio_i_69a34f_idx'),
        ),
        migrations.AddIndex(
            model_name='radioassignment',
            index=models.Index(fields=['endpoint', 'end_at'], name='inventory_r_endpoin_3307a3_idx'),
        ),
        migrations.AddConstraint(
            model_name='radioassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('end_at__isnull', True)), fields=('radio',), name='uniq_open_assignment_per_radio'),
        ),
    ]
