# Generated by Django 4.2.23 on 2025-12-24 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('fireplan', '0005_fireplanfiliere_fireplangrade_fireplangroup_and_more'),
        ('inventory', '0005_radiocontainer_locationcontainer_radioendpoint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationcontainer',
            name='radiocontainer_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.radiocontainer'),
        ),
        migrations.AlterField(
            model_name='radiocontainer',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='vectorcontainer',
            name='radiocontainer_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.radiocontainer'),
        ),
        migrations.AlterField(
            model_name='vectorcontainer',
            name='vector',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fireplan.vector'),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('service', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_post', to='fireplan.service')),
            ],
        ),
        migrations.AddField(
            model_name='vectorcontainer',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.post'),
        ),
    ]
