# Generated by Django 4.2.23 on 2026-01-13 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('fireplan', '0007_fireplaninventory_vehicle'),
        ('inventory', '0013_alter_locationcontainer_radiocontainer_ptr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationcontainer',
            name='radiocontainer_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.radiocontainer'),
        ),
        migrations.AlterField(
            model_name='radiocontainer',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='vectorcontainer',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.post'),
        ),
        migrations.AlterField(
            model_name='vectorcontainer',
            name='radiocontainer_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.radiocontainer'),
        ),
        migrations.AlterField(
            model_name='vectorcontainer',
            name='vector',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fireplan.vector'),
        ),
    ]
