# Generated by Django 4.2.23 on 2026-08-18 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fireplan', '0013_make_inventory_uuids_optional'),
        ('radio', '0023_use_full_15_digit_tei'),
        ('inventory', '0015_alter_locationcontainer_radiocontainer_ptr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location_type', models.CharField(choices=[('POST', 'Post'), ('DISPATCH', 'Dispatching'), ('STOCK', 'Stock'), ('SMART_CABINET', 'Intelligent cabinet'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='inventory.location')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='fireplan.service')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RadioPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='radio_positions', to='inventory.location')),
                ('vector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='radio_positions', to='fireplan.vector')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='radio_positions', to='fireplan.vehicle')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RadioPositionAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PRIMARY', 'Primary'), ('SUBSTITUTE', 'Substitute')], max_length=20)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_position_assignments', to=settings.AUTH_USER_MODEL)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='inventory.radioposition')),
                ('radio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='position_assignments', to='radio.radio')),
                ('replaces', models.ForeignKey(blank=True, help_text='Primary assignment replaced by this substitute.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='substitute_assignments', to='inventory.radiopositionassignment')),
            ],
            options={
                'ordering': ['-assigned_at', '-id'],
                'indexes': [models.Index(fields=['radio', 'ended_at'], name='inventory_r_radio_i_e04c6c_idx'), models.Index(fields=['position', 'role', 'ended_at'], name='inventory_r_positio_97cf0c_idx'), models.Index(fields=['position', '-assigned_at'], name='inventory_r_positio_07b391_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='radiopositionassignment',
            constraint=models.CheckConstraint(check=models.Q(('ended_at__isnull', True), ('ended_at__gt', models.F('assigned_at')), _connector='OR'), name='assignment_ends_after_start'),
        ),
        migrations.AddConstraint(
            model_name='radiopositionassignment',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('replaces__isnull', True), ('role', 'PRIMARY')), models.Q(('replaces__isnull', False), ('role', 'SUBSTITUTE')), _connector='OR'), name='assignment_replaces_by_role'),
        ),
        migrations.AddConstraint(
            model_name='radiopositionassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('radio',), name='uniq_active_assignment_per_radio'),
        ),
        migrations.AddConstraint(
            model_name='radiopositionassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True), ('role', 'PRIMARY')), fields=('position',), name='uniq_active_primary_per_position'),
        ),
        migrations.AddConstraint(
            model_name='radiopositionassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True), ('role', 'SUBSTITUTE')), fields=('position',), name='uniq_active_sub_per_position'),
        ),
        migrations.AddIndex(
            model_name='radioposition',
            index=models.Index(fields=['vector', 'order', 'name'], name='inventory_r_vector__48a54c_idx'),
        ),
        migrations.AddIndex(
            model_name='radioposition',
            index=models.Index(fields=['vehicle', 'order', 'name'], name='inventory_r_vehicle_1003bb_idx'),
        ),
        migrations.AddIndex(
            model_name='radioposition',
            index=models.Index(fields=['location', 'order', 'name'], name='inventory_r_locatio_dc1941_idx'),
        ),
        migrations.AddConstraint(
            model_name='radioposition',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('location__isnull', True), ('vector__isnull', False), ('vehicle__isnull', True)), models.Q(('location__isnull', True), ('vector__isnull', True), ('vehicle__isnull', False)), models.Q(('location__isnull', False), ('vector__isnull', True), ('vehicle__isnull', True)), _connector='OR'), name='position_exactly_one_parent'),
        ),
        migrations.AddConstraint(
            model_name='radioposition',
            constraint=models.UniqueConstraint(condition=models.Q(('vector__isnull', False)), fields=('vector', 'name'), name='uniq_position_name_per_vector'),
        ),
        migrations.AddConstraint(
            model_name='radioposition',
            constraint=models.UniqueConstraint(condition=models.Q(('vehicle__isnull', False)), fields=('vehicle', 'name'), name='uniq_position_name_per_vehicle'),
        ),
        migrations.AddConstraint(
            model_name='radioposition',
            constraint=models.UniqueConstraint(condition=models.Q(('location__isnull', False)), fields=('location', 'name'), name='uniq_position_name_per_location'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('parent', 'name'), name='uniq_location_name_per_parent'),
        ),
    ]
