# Generated by Django 4.2.23 on 2026-08-25 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fireplan', '0014_vector_display_name'),
        ('inventory', '0018_delete_legacy_position_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='dashboard_locations',
            field=models.ManyToManyField(blank=True, help_text='Additional locations that belong to this dashboard/location.', related_name='included_in_dashboards', to='inventory.location'),
        ),
        migrations.AddField(
            model_name='location',
            name='dashboard_vectors',
            field=models.ManyToManyField(blank=True, help_text='Vectors that belong to this dashboard/location.', related_name='dashboard_locations', to='fireplan.vector'),
        ),
    ]
