# Generated by Django 5.2.3 on 2025-07-02 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ISSI',
            fields=[
                ('number', models.BigIntegerField(primary_key=True, serialize=False)),
                ('alias', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Radio',
            fields=[
                ('TEI', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radio.issi')),
                ('radio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radio.radio')),
            ],
            options={
                'unique_together': {('radio', 'issi')},
            },
        ),
    ]
