# Generated by Django 5.2.3 on 2025-07-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='astrid_alias',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
