# Generated by Django 4.2.23 on 2025-07-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0002_subscription_astrid_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='radio',
            name='fireplan_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
