# Generated by Django 4.2.23 on 2025-07-05 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0003_radio_fireplan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='issi',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='radio.issi'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='radio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='radio.radio'),
        ),
    ]
