# Generated by Django 4.2.23 on 2025-07-15 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0004_alter_subscription_issi_alter_subscription_radio'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('ATEX', models.BooleanField(default=False)),
            ],
        ),
    ]
