# Generated by Django 4.2.23 on 2025-07-15 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0005_radiomodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TEIRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_tei', models.BigIntegerField()),
                ('max_tei', models.BigIntegerField()),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radio.radiomodel')),
            ],
        ),
    ]
