# Generated by Django 4.2.23 on 2025-07-15 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0006_teirange'),
    ]

    operations = [
        migrations.RenameField(
            model_name='radiomodel',
            old_name='ATEX',
            new_name='is_atex',
        ),
    ]
