# Generated by Django 4.2.23 on 2025-07-15 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0007_rename_atex_radiomodel_is_atex'),
    ]

    operations = [
        migrations.AddField(
            model_name='radio',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='radio.radiomodel'),
        ),
    ]
