# Generated by Django 4.2.23 on 2025-07-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0009_customer_issicustomerrange_issi_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radio',
            name='fireplan_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
