# Generated by Django 4.2.23 on 2025-07-15 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0012_discipline_issidisciplinerange'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issidisciplinerange',
            old_name='name',
            new_name='discipline',
        ),
    ]
