# Generated by Django 4.2.23 on 2025-07-15 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0013_rename_name_issidisciplinerange_discipline'),
    ]

    operations = [
        migrations.AddField(
            model_name='issi',
            name='discipline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='radio.discipline'),
        ),
    ]
