# Generated by Django 4.2.23 on 2025-07-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0014_issi_discipline'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='bootstrap_class',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
