# Generated by Django 4.2.23 on 2025-07-17 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0015_discipline_bootstrap_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issi',
            name='alias',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
