# Generated by Django 4.2.23 on 2025-09-10 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0016_alter_issi_alias'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'permissions': [('can_upload_subscriptions', 'Can upload a subscriptions export from Astrid')]},
        ),
    ]
