# Generated by Django 4.2.23 on 2025-09-21 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0017_alter_subscription_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='radio',
            name='decommissioned',
            field=models.BooleanField(default=False),
        ),
    ]
