# Generated by Django 4.2.23 on 2025-09-30 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0006_alter_ticketlog_options'),
        ('radio', '0018_radio_decommissioned'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadioDecommissioningTicket',
            fields=[
                ('ticket_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='helpdesk.ticket')),
            ],
            options={
                'permissions': [('can_create_decommission_requests', 'Can create a decommission request'), ('can_approve_decommission_requests', 'Can approve a decommission request')],
            },
            bases=('helpdesk.ticket',),
        ),
    ]
