# Generated by Django 4.2.23 on 2025-09-30 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0019_radiodecommissioningticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiomodel',
            name='radio_type',
            field=models.CharField(choices=[('PORTABLE', 'Portable'), ('MOBILE', 'Mobile')], default='PORTABLE', max_length=10),
        ),
    ]
