# Generated by Django 4.2.23 on 2025-10-09 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0020_radiomodel_radio_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='DMO_only',
            field=models.BooleanField(default=False),
        ),
    ]
