# Generated by Django 4.2.23 on 2025-12-09 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0021_subscription_dmo_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='discipline_type',
            field=models.CharField(choices=[('PORTABLE', 'Police'), ('FIRE', 'Fire'), ('MEDICAL', 'Medical'), ('OTHER', 'Other')], default='OTHER', max_length=10),
        ),
    ]
