# Generated by Django 4.2.23 on 2025-09-14 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('radio', '0017_alter_subscription_options'),
        ('organization', '0015_container_show_in_listing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('location', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CabinetSlot',
            fields=[
                ('radiocontainerlink_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='organization.radiocontainerlink')),
                ('state', models.CharField(choices=[('empty', 'Empty'), ('spare', 'Spare radio'), ('defect', 'Defecte radio'), ('in_use', 'In use')], default='empty', max_length=20)),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='traca.cabinet')),
            ],
            options={
                'ordering': ['cabinet', 'name'],
            },
            bases=('organization.radiocontainerlink',),
        ),
        migrations.CreateModel(
            name='CabinetLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('taken', 'Taken'), ('returned', 'Returned'), ('swap', 'Swap')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('radio_in', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_in', to='radio.radio')),
                ('radio_out', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_out', to='radio.radio')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='traca.cabinetslot')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
