# Generated by Django 4.2.23 on 2025-11-16 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceTypeCode',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StatusCode',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('description_nl', models.CharField(max_length=100, null=True)),
                ('description_fr', models.CharField(max_length=100, null=True)),
                ('description_en', models.CharField(max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=50)),
                ('call_sign', models.CharField(blank=True, max_length=50)),
                ('num_letter', models.CharField(max_length=5)),
                ('num_value', models.IntegerField()),
                ('plate', models.CharField(max_length=20)),
                ('utilisation', models.CharField(max_length=200)),
                ('chassis', models.CharField(max_length=100)),
                ('status', models.IntegerField(choices=[(1, 'Actif'), (2, 'Rebuté'), (3, 'Préparation')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vector',
            fields=[
                ('resourceCode', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('abbreviation', models.CharField(blank=True, max_length=50)),
                ('orderServiceAbbreviation', models.CharField(blank=True, max_length=200, null=True)),
                ('resourceTypeCode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fireplan.resourcetypecode')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fireplan.service')),
                ('statusCode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fireplan.statuscode')),
                ('vehicle', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vector', to='fireplan.vehicle')),
            ],
        ),
    ]
