# Generated by Django 4.2.23 on 2025-11-17 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0021_subscription_dmo_only'),
        ('fireplan', '0002_fill_statuscodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='radio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='radio.radio'),
        ),
    ]
