# Generated by Django 4.2.23 on 2025-11-22 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0021_subscription_dmo_only'),
        ('fireplan', '0003_vehicle_radio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='radio',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle', to='radio.radio'),
        ),
    ]
