# Generated by Django 4.2.23 on 2025-12-01 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fireplan', '0004_alter_vehicle_radio'),
    ]

    operations = [
        migrations.CreateModel(
            name='FireplanFiliere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FireplanGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('name_nl', models.CharField(max_length=150, null=True, unique=True)),
                ('name_fr', models.CharField(max_length=150, null=True, unique=True)),
                ('name_en', models.CharField(max_length=150, null=True, unique=True)),
                ('abbrev', models.CharField(blank=True, max_length=20)),
                ('abbrev_nl', models.CharField(blank=True, max_length=20, null=True)),
                ('abbrev_fr', models.CharField(blank=True, max_length=20, null=True)),
                ('abbrev_en', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FireplanGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FireplanLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('label', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FireplanSubGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FireplanProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fireplan_username', models.CharField(help_text='Username used to log in to Fireplan', max_length=150, unique=True)),
                ('filiere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='fireplan.fireplanfiliere')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='fireplan.fireplangrade')),
                ('groups', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='fireplan.fireplangroup')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='fireplan.fireplanlanguage')),
                ('subgroups', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='fireplan.fireplansubgroup')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fireplan_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
