# Generated by Django 4.2.23 on 2026-01-13 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0022_discipline_discipline_type'),
        ('fireplan', '0005_fireplanfiliere_fireplangrade_fireplangroup_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FireplanInventory',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('vehicle_alpha_code', models.CharField(db_index=True, max_length=16)),
                ('closed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('done_by_full_name', models.CharField(blank=True, default='', max_length=128)),
                ('overseen_by_full_name', models.CharField(blank=True, default='', max_length=128)),
                ('root_inventoried_container_uuid', models.UUIDField(blank=True, db_index=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FireplanInventoryRadio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_uuid', models.UUIDField(db_index=True)),
                ('item_uuid', models.UUIDField(db_index=True)),
                ('tracked_item_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('tei', models.CharField(db_index=True, max_length=64)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radios', to='fireplan.fireplaninventory')),
                ('radio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fireplan_inventory_radios', to='radio.radio')),
            ],
        ),
        migrations.AddConstraint(
            model_name='fireplaninventoryradio',
            constraint=models.UniqueConstraint(fields=('inventory', 'item_uuid'), name='uniq_fireplan_inventory_radio_item'),
        ),
    ]
