# Generated by Django 4.2.23 on 2026-01-13 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fireplan', '0006_fireplaninventory_fireplaninventoryradio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fireplaninventory',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventories', to='fireplan.vehicle'),
        ),
    ]
