# Generated by Django 4.2.23 on 2026-06-04 19:58

from django.db import migrations, models


def copy_vehicle_pk_to_fireplan_id(apps, schema_editor):
    Vehicle = apps.get_model("fireplan", "Vehicle")
    for vehicle in Vehicle.objects.filter(fireplan_id__isnull=True):
        vehicle.fireplan_id = vehicle.id
        vehicle.save(update_fields=["fireplan_id"])


def ensure_postgres_vehicle_id_sequence(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return

    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SELECT pg_get_serial_sequence('fireplan_vehicle', 'id')")
        sequence_name = cursor.fetchone()[0]
        if not sequence_name:
            return

        cursor.execute(
            """
            SELECT setval(
                %s,
                COALESCE((SELECT MAX(id) FROM fireplan_vehicle), 1),
                true
            )
            """,
            [sequence_name],
        )


class Migration(migrations.Migration):

    dependencies = [
        ('fireplan', '0009_link_legacy_14_digit_inventory_radios'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='fireplan_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.RunPython(copy_vehicle_pk_to_fireplan_id, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='vehicle',
            name='chassis',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.RunPython(ensure_postgres_vehicle_id_sequence, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='vehicle',
            name='num_letter',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='num_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='plate',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='utilisation',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
