# Generated by Django 4.2.23 on 2026-06-04 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0023_use_full_15_digit_tei'),
        ('fireplan', '0010_vehicle_fireplan_id_alter_vehicle_chassis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='issi',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle', to='radio.issi'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.CheckConstraint(check=models.Q(('radio__isnull', True), ('issi__isnull', True), _connector='OR'), name='vehicle_radio_or_issi_not_both'),
        ),
    ]
