# Generated by Django 4.2.23 on 2026-08-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fireplan', '0013_make_inventory_uuids_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='vector',
            name='display_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
